# Generated by Django 3.2.4 on 2021-07-29 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancy', '0004_auto_20210723_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciality',
            name='picture',
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('NR', 'Не ищу работу'), ('RF', 'Рассматриваю предложения'), ('RW', 'Ищу работу')], default='NR', max_length=2)),
                ('salary', models.IntegerField()),
                ('speciality', models.CharField(max_length=120)),
                ('grade', models.CharField(choices=[('IN', 'Стажер'), ('JN', 'Младший разработчик'), ('MD', 'Разработчик'), ('LD', 'Ведущий разработчик')], default='IN', max_length=2)),
                ('education', models.CharField(max_length=120)),
                ('experience', models.IntegerField()),
                ('portfolio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
