# Generated by Django 3.2.4 on 2021-07-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0006_alter_resume_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='portfolio',
            field=models.URLField(),
        ),
    ]
